# Generated by Django 4.2.5 on 2023-09-19 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinacursos',
            name='nome',
        ),
        migrations.AddField(
            model_name='disciplinacursos',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
            preserve_default=False,
        ),
    ]
